version: '3.8'

services:
  activemq:
    image: apache/activemq-artemis
    container_name: activemq
    ports:
      - "8161:8161"  # Consola web de ActiveMQ
      - "61616:61616"  # Conexiones de clientes OpenWire
      - "61613:61613"  # Conexiones de clientes STOMP 
      - "5672:5672"    # Conexiones de clientes AMQP
      - "1883:1883"    # Conexiones de clientes MQTT
    environment:
      ARTEMIS_USER: "admin"
      ARTEMIS_PASSWORD: "admin"
      DISABLE_SECURITY: 'false'
      ACTIVEMQ_MIN_MEMORY: 1024
      ACTIVEMQ_MAX_MEMORY: 2048
    volumes:
      - activemq-data:/data
      - activemq-logs:/var/log/activemq

volumes:
  activemq-data:
  activemq-logs: